package com.team271.frc2026.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.team271.frc2026.generated.TunerConstants.TunerSwerveDrivetrain;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class TimedSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double SIM_LOOP_PERIOD = 0.004; // 4 ms
    private Notifier mSimNotifier = null;
    private double mLastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d BLUE_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d RED_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean mHasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation mTranslationCharacterization =
            new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains mSteerCharacterization =
            new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation mRotationCharacterization =
            new SwerveRequest.SysIdSwerveRotation();

    /*
     * SysId routine for characterizing translation. This is used to find PID gains
     * for the drive motors.
     */
    private final SysIdRoutine mSysIdRoutineTranslation =
            new SysIdRoutine(
                    new SysIdRoutine.Config(
                            null, // Use default ramp rate (1 V/s)
                            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
                            null, // Use default timeout (10 s)
                            // Log state with SignalLogger class
                            state ->
                                    SignalLogger.writeString(
                                            "SysIdTranslation_State", state.toString())),
                    new SysIdRoutine.Mechanism(
                            output -> setControl(mTranslationCharacterization.withVolts(output)),
                            null,
                            this));

    /*
     * SysId routine for characterizing steer. This is used to find PID gains for
     * the steer motors.
     */
    private final SysIdRoutine mSysIdRoutineSteer =
            new SysIdRoutine(
                    new SysIdRoutine.Config(
                            null, // Use default ramp rate (1 V/s)
                            Volts.of(7), // Use dynamic voltage of 7 V
                            null, // Use default timeout (10 s)
                            // Log state with SignalLogger class
                            state ->
                                    SignalLogger.writeString("SysIdSteer_State", state.toString())),
                    new SysIdRoutine.Mechanism(
                            volts -> setControl(mSteerCharacterization.withVolts(volts)),
                            null,
                            this));

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle
     * HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
     * importing the log to SysId.
     */
    private final SysIdRoutine mSysIdRoutineRotation =
            new SysIdRoutine(
                    new SysIdRoutine.Config(
                            /* This is in radians per second^2, but SysId only supports "volts per second" */
                            Volts.of(Math.PI / 6).per(Second),
                            /* This is in radians per second, but SysId only supports "volts" */
                            Volts.of(Math.PI),
                            null, // Use default timeout (10 s)
                            // Log state with SignalLogger class
                            state ->
                                    SignalLogger.writeString(
                                            "SysIdRotation_State", state.toString())),
                    new SysIdRoutine.Mechanism(
                            output -> {
                                /* output is actually radians per second, but SysId only supports "volts" */
                                setControl(
                                        mRotationCharacterization.withRotationalRate(
                                                output.in(Volts)));
                                /* also log the requested output for SysId */
                                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
                            },
                            null,
                            this));

    /* The SysId routine to test */
    private SysIdRoutine mSysIdRoutineToApply = mSysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param argDrivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param argModules Constants for each specific module
     */
    public TimedSwerveDrivetrain(
            final SwerveDrivetrainConstants argDrivetrainConstants,
            final SwerveModuleConstants<?, ?, ?>... argModules) {
        super(argDrivetrainConstants, argModules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param argDrivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param argOdometryUpdateFrequency The frequency to run the odometry loop. If unspecified or
     *     set to 0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
     * @param argModules Constants for each specific module
     */
    public TimedSwerveDrivetrain(
            final SwerveDrivetrainConstants argDrivetrainConstants,
            final double argOdometryUpdateFrequency,
            final SwerveModuleConstants<?, ?, ?>... argModules) {
        super(argDrivetrainConstants, argOdometryUpdateFrequency, argModules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     *
     * <p>This constructs the underlying hardware devices, so users should not construct the devices
     * themselves. If they need the devices, they can access them through getters in the classes.
     *
     * @param argDrivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param argOdometryUpdateFrequency The frequency to run the odometry loop. If unspecified or
     *     set to 0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
     * @param argOdometryStandardDeviation The standard deviation for odometry calculation in the
     *     form [x, y, theta]^T, with units in meters and radians
     * @param argVisionStandardDeviation The standard deviation for vision calculation in the form
     *     [x, y, theta]^T, with units in meters and radians
     * @param argModules Constants for each specific module
     */
    public TimedSwerveDrivetrain(
            final SwerveDrivetrainConstants argDrivetrainConstants,
            final double argOdometryUpdateFrequency,
            final Matrix<N3, N1> argOdometryStandardDeviation,
            final Matrix<N3, N1> argVisionStandardDeviation,
            final SwerveModuleConstants<?, ?, ?>... argModules) {
        super(
                argDrivetrainConstants,
                argOdometryUpdateFrequency,
                argOdometryStandardDeviation,
                argVisionStandardDeviation,
                argModules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param argRequest Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(final Supplier<SwerveRequest> argRequest) {
        return run(() -> this.setControl(argRequest.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
     * #mSysIdRoutineToApply}.
     *
     * @param argDirection Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(final SysIdRoutine.Direction argDirection) {
        return mSysIdRoutineToApply.quasistatic(argDirection);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
     * #mSysIdRoutineToApply}.
     *
     * @param argDirection Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(final SysIdRoutine.Direction argDirection) {
        return mSysIdRoutineToApply.dynamic(argDirection);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply
         * it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts
         * mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is
         * disabled.
         * This ensures driving behavior doesn't change until an explicit disable event
         * occurs during testing.
         */
        if (!mHasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance()
                    .ifPresent(
                            allianceColor -> {
                                setOperatorPerspectiveForward(
                                        allianceColor == Alliance.Red
                                                ? RED_ALLIANCE_PERSPECTIVE_ROTATION
                                                : BLUE_ALLIANCE_PERSPECTIVE_ROTATION);
                                mHasAppliedOperatorPerspective = true;
                            });
        }
    }

    private void startSimThread() {
        mLastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        mSimNotifier =
                new Notifier(
                        () -> {
                            final double currentTime = Utils.getCurrentTimeSeconds();
                            double deltaTime = currentTime - mLastSimTime;
                            mLastSimTime = currentTime;

                            /* use the measured time delta, get battery voltage from WPILib */
                            updateSimState(deltaTime, RobotController.getBatteryVoltage());
                        });
        mSimNotifier.startPeriodic(SIM_LOOP_PERIOD);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param argVisionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param argTimestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(
            final Pose2d argVisionRobotPoseMeters, final double argTimestampSeconds) {
        super.addVisionMeasurement(
                argVisionRobotPoseMeters, Utils.fpgaToCurrentTime(argTimestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * <p>Note that the vision measurement standard deviations passed into this method will continue
     * to apply to future measurements until a subsequent call to {@link
     * #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param argVisionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param argTimestampSeconds The timestamp of the vision measurement in seconds.
     * @param argVisionMeasurementStdDevs Standard deviations of the vision pose measurement in the
     *     form [x, y, theta]^T, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            final Pose2d argVisionRobotPoseMeters,
            final double argTimestampSeconds,
            final Matrix<N3, N1> argVisionMeasurementStdDevs) {
        super.addVisionMeasurement(
                argVisionRobotPoseMeters,
                Utils.fpgaToCurrentTime(argTimestampSeconds),
                argVisionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param argTimestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(final double argTimestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(argTimestampSeconds));
    }
}
